# For inspiration : https://github.com/tiangolo/full-stack-fastapi-postgresql
services:
  db:
    env_file:
      - .env
    container_name: ${POSTGRES_HOSTNAME:-postgres-db}
    image: postgres:latest
    volumes:
      - versus-db-data:${POSTGRES_DATA:-/var/lib/postgresql/data/pgdata}
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    restart: unless-stopped
    networks:
      - versus-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    profiles: ['qualif'] # docker-compose --profile qualif up pour avoir également pgadmin
    env_file:
      - .env
    networks:
      - versus-network
    ports:
      - '${PGADMIN_HOST_PORT:-5050}:${PGADMIN_LISTEN_PORT:-80}'
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  versus-db-data:
  pgadmin-data:

networks:
  versus-network:
